### ISSUE TITLE
Meetup.com API

### ISSUE THREAD

**Issue by allella** [codeforgreenville/OpenData#12]
http://www.meetup.com/meetup_api/

**Comment by allella** [comment]
Console for testing the API https://secure.meetup.com/meetup_api/console/?path=/2/groups

**Comment by allella** [comment]
How to lookup a group's ID via their URL name
https://github.com/codeforgreenville/UpstateEvents/issues/15#issuecomment-68424187

**Comment by nullvariable** [comment]
Here's a nice PHP library for pulling data from the meetup.com api

https://github.com/rdohms/meetup-api-client

**Comment by Nunie123** [comment]
@allella I've made good progress on the API for meetup.  The Meetup API Key for Greer Programming Group is listed on the Open Data website as '7709021031', but this is incorrect and throws an error when I try to use it with the Meetup API.  Currently I'm excluding this group from the Meetup API call.  

I'm working on this issue here: https://github.com/Nunie123/upstate_tech_cal_service

**Comment by allella** [comment]
@Nunie123 if you message me your email I'll set you up with access to change the underlying data. Or, did I already set up an account?

**Comment by Nunie123** [comment]
@allela I have this working.  

The API is running and available at: http://nunes.online/api/gtc

The code for the application is here: https://github.com/Nunie123/upstate_tech_cal_service

Only Meetup.com and EventBrite.com are supported.  Other sources, such as facebook, Nvite, Open Collective, had issues that prevented API calls to them to be fully automated.  We can discuss further about possible ways to include these sites.

The data is update every 5 minutes.

The endpoint does not support filtering currently.  That wouldn't be too hard to implement, but I'd rather talk with someone who intends to use it instead of guessing use cases.

It is hosted on AWS and I'm on my free tier, so currently no cost to host.  If we want/need to change host, it's running on a generic ubuntu box, so shouldn't be hard to move.

**Comment by allella** [comment]
Rock on.

I'll try to poke around a bit during the holiday break.

I should be around for the 28th meeting and we can chat and dig in.

**Comment by allella** [comment]
@Nunie123 

I took a look at the data and the first notable item is the Eventbrite data looks to be pulling in events from 10 years earlier.

I'd imagine more of the use cases will on upcoming or recent events so perhaps a filter for past vs future/current would be a useful first filter and keep the payload a lot smaller for the future/recent use cases.  Thoughts on that situation?

**Comment by Nunie123** [comment]
@allella 

I agree with you that past events data doesn't have a lot of value.  Meetup doesn't even provide past events, so you can only look retrospectively at EventBrite events.  

The question is whether to simply get rid of it, make a separate endpoint for future events only, or accept post requests indicating future events only.  Right now I'm thinking Id just make a separate endpoint.

**Comment by Nunie123** [comment]
I have updated the endpoint to go over https.

I've also added date filter options to the endpoint.  By default it now provides only future events.  A `start_date` and `end_date` can be specified in the URL to get specific date ranges.  I've updated the readme with more detail on how to use it.

I've created a front-end that runs off this data, which can be viewed here: https://nunie123.github.io/gtc/.  The repo is here: https://github.com/Nunie123/gtc.  @tomatohorse, from the last meeting, is helping me with design for the front-end.

At the last meeting I was sent an invite to contribute to the codeforgreenville github, but I do not have permission to create new repositories.  We had talked about migrating my repos to codeforgreenville, but I'm unsure of the best strategy for doing so.  Does it makes sense to just fork them, or do we want some other setup?

**Comment by allella** [comment]
Good work.

@Nunie123 You should now be able to create a new repository under the CFG Github so you're welcome to move things over as you see fit.

**Comment by Nunie123** [comment]
@allela The api has been updated to include flag filter parameters, in addition to date parameters (e.g. http://nunes.online/api/gtc?tags=1).  Currently it returns an empty array because the only group that has tags, UpstatePHP, does not host events on meetup.com or eventbrite.com.

Let's move further discussion to the repo: https://github.com/codeforgreenville/upstate_tech_cal_service

**Comment by allella** [comment]
@Nunie123 I've enabled Issues on the upstate_tech_cal_service repo. Feel free to create any open issues there and we can close the issues here and link them to each other for future reference.

**Comment by allella** [comment]
Closing this issue.

For history, see above. For future conversation on the [meetup.com bot](https://github.com/codeforgreenville/upstate_tech_cal_service/issues/3) and Ed's new [upstate_tech_cal_service](https://github.com/codeforgreenville/upstate_tech_cal_service) repo.

**Comment by allella** [comment]
Wayback Machine has copies of the old v2 REST API docs, which were removed and redirected to the [GraphQL](https://github.com/hackgvl/hackgreenville-com/issues/212) docs awhile back.

[v2 REST API - GET /events](https://web.archive.org/web/20170709041824/http://www.meetup.com/meetup_api/docs/2/events/)
[v2 REST API - GET /groups](https://web.archive.org/web/20170709041556/http://www.meetup.com/meetup_api/docs/2/groups/)
