### ISSUE TITLE
RESCUE -  SC Codes Students' Google spreadsheets -> to Code for Greenville's Google Docs

### ISSUE THREAD

**Issue by Mozillex** [codeforgreenville/OpenData#48]
@allella , It appears that a number of the SC Codes students' Google spreadsheets were inadvertently 'deleted,' and are in SC Codes' Google Docs Trash bin.
These spreadsheets need to be copied/backed up over to Code for Greenville's Google Docs ASAP, before these docs are lost forever.

**Comment by MarkHetu** [comment]
I will start inventorying current spreadsheets and determine current status of each.

**Comment by allella** [comment]
@walkreed
The art galleries spreadsheet is now under a Code For Greenville spreadsheet as shown at
https://data.openupstate.org/map/art-galleries
please make any future edits on this spreadsheet.

@MarkHetu  @ahmeloc
The bike rack spreadsheet is now under a Code For Greenville spreadsheet.
https://data.openupstate.org/map/bike-racks
please make any future edits on this spreadsheet.

**Comment by allella** [comment]
@sparklebunny @Unicorned @kfricks

The breweries spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash
https://data.openupstate.org/map/breweries
Please click the contribute link to request edit rights and you may continue to make future edits on this new spreadsheet.
https://data.openupstate.org/map/breweries

**Comment by allella** [comment]
@jdesmond79

The Children's Parks spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at https://data.openupstate.org/map/childrens-parks

You should have received an invite to edit the new spreadsheet and may continue to make future edits on this new copy.

**Comment by allella** [comment]
@Ofrazzle

The City Halls spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at https://data.openupstate.org/map/city-halls

I don't have your email but if you click the View Only button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@Jaaron0606 

The City Parks - Greenville spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at https://data.openupstate.org/map/city-parks-greenville

You should have received an invite to edit the new spreadsheet and may continue to make future edits on this new copy.

**Comment by allella** [comment]
@assete

The City Parks - Greer spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at https://data.openupstate.org/map/city-parks-greer

You should have received an invite to edit the new spreadsheet and may continue to make future edits on this new copy.

**Comment by allella** [comment]
@leojnewman

The Community Gardens spreadsheet is now under a Code For Greenville account since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at https://data.openupstate.org/map/community-gardens

You should have received an invite to edit the new spreadsheet and may continue to make future edits on this new copy.

**Comment by allella** [comment]
The Dog Parks spreadsheet is now under a Code For Greenville account since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at https://data.openupstate.org/map/dog-parks

You should have received an invite to edit the new spreadsheet and may continue to make future edits on this new copy.

**Comment by allella** [comment]
@LHewlett46

The Dog Waste spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at 
https://data.openupstate.org/map/dog-waste-bags

I don't have your email but if you click the View Only button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@sparklebunny
@schemmelsc
@bonvisuals
@cacoding

The Dog spreadsheets are now under a Code For Greenville account since we've had a handful of spreadsheets end up in individual's trash. The contribute links are shown at https://data.openupstate.org/map/dog-parks
https://data.openupstate.org/map/dog-friendly-restaurants-and-bars
https://data.openupstate.org/map/dog-friendly-retail-stores

You should have received an invite to edit the new spreadsheet and may continue to make future edits on this new copy.

**Comment by allella** [comment]
@ses29680 @nine6era

The EV Charger spreadsheets are now under a Code For Greenville account since we've had a handful of spreadsheets end up in individual's trash. The contribute links are shown at 
https://data.openupstate.org/map/electric-vehicle-charging-stations

You should have the ability to edit the new spreadsheet and may continue to make future edits on this new copy.

**Comment by allella** [comment]
@vzambrano98 @cplklegg

The following spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at

https://data.openupstate.org/map/farmers-markets

I don't have your email set for editing then you may click the View Only button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@sweenz @Sln218

The following spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at

https://data.openupstate.org/map/fishing-access-sites

I don't have your email set for editing then you may click the View Only button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@michael-rooney

The following spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at

https://data.openupstate.org/map/foothills-trail-access

I don't have your email set for editing then you may click the View Only button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@lizziemeeker

The following spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at

https://data.openupstate.org/map/free-job-training-resources

I don't have your email set for editing then you may click the View Only button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@ktmensing

The following spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at

https://data.openupstate.org/map/greer-public-parking

You should have the ability to edit the new spreadsheet and may continue to make future edits on this new copy.

**Comment by allella** [comment]
@lorieo828 

The following spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at

https://data.openupstate.org/map/higher-education

I don't have your email set for editing then you may click the View Only button on the new spreadsheet it will send a request for access and we'll make you an editor again.

@Iggy1906
You should have the ability to edit the new spreadsheet and may continue to make future edits on this new copy.

**Comment by allella** [comment]
@sfunk3 @everydaynerd @sraines

The following spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at

https://data.openupstate.org/map/historic-sites

I don't have your email set for editing then you may click the View Only button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@jlew1914

The following spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at

https://data.openupstate.org/map/historical-african-american-churches

I don't have your email set for editing then you may click the View Only button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@magoun

The following spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at

https://data.openupstate.org/map/mice-on-main

You should have the ability to edit the new spreadsheet and may continue to make future edits on this new copy.

**Comment by allella** [comment]
@Juicysmo @jeremiahadkins

The following spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at

https://data.openupstate.org/map/music-venues

You should have the ability to edit the new spreadsheet and may continue to make future edits on this new copy.

**Comment by allella** [comment]
@shelbymcohen @GBClemson @artshra

The following spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at

https://data.openupstate.org/map/organic-farms

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@BethanyWinston

The following spreadsheet is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash. The contribute link is shown at

https://data.openupstate.org/map/parking-decks

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@meenasrik 

https://data.openupstate.org/map/schools-k12

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@gracekmosley

https://data.openupstate.org/map/public-restrooms-downtown

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@johnchristmas

https://data.openupstate.org/map/public-running-tracks

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@embee3

https://data.openupstate.org/map/quilting-quilds

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@danieltapp @thgr8rs

https://data.openupstate.org/map/recreation-basketball-courts

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@pa822

https://data.openupstate.org/map/roller-skating-and-skateboarding

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@valkyrie1317

https://data.openupstate.org/map/solid-waste

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@levimonday

https://data.openupstate.org/map/swamp-rabbit-trail-entrances

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@cdhorn515

https://data.openupstate.org/map/swamp-rabbit-trail-mile-markers

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@calebmcquaid @Andr3wB 

https://data.openupstate.org/map/swamp-rabbit-trail-water-fountains

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@sagapato 

https://data.openupstate.org/map/swimming-pools

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@EdensLamb

https://data.openupstate.org/map/falls-park-benches

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@hollyv04 @garrison44 @MattAHarvey
https://data.openupstate.org/map/tent-camping

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@davidgalloway

https://data.openupstate.org/map/historic-textile-mills

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@jenrobert

https://data.openupstate.org/map/walking-trails

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.

**Comment by allella** [comment]
@kbarbs

https://data.openupstate.org/map/wall-murals

The spreadsheet above is now under a Code For Greenville spreadsheet since we've had a handful of spreadsheets end up in individual's trash.

If you don't have the ability to edit the new spreadsheet you may click the "View Only" button on the new spreadsheet it will send a request for access and we'll make you an editor again.
